(defun addnums ()
  (princ "Add two numbers = ")
  (write (+ (read) (read))))
(defun multiply ()
  (princ "Multiply two numbers = ")(write (* (read)(read))))
(defun divide ()
  (princ "Divide two numbers = ")
  (write (/ (read) (read))))
